import { KnobParameters, KnobShape, ShaftType } from '../types';

export interface KnobPreset {
  name: string;
  description: string;
  params: KnobParameters;
  tags: string[];
}

export const KNOB_PRESETS: KnobPreset[] = [
  {
    name: "Classic Davies 1900",
    description: "Vintage amp-style knob with smooth cylinder",
    params: {
      diameter: 20,
      height: 15,
      shape: KnobShape.CYLINDER,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 12,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#ff6b35",
      pointerIndent: true,
      pointerColor: "#ffffff",
      polygonSides: 6,
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 18,
    },
    tags: ["vintage", "smooth", "classic"],
  },
  {
    name: "Modern Aluminum",
    description: "Machined-look knob with fluted grip",
    params: {
      diameter: 18,
      height: 18,
      shape: KnobShape.FLUTED,
      fluteCount: 24,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 14,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#4a90e2",
      pointerIndent: true,
      pointerColor: "#ff0000",
      polygonSides: 6,
      skirtHeight: 0,
      skirtDiameter: 16,
    },
    tags: ["modern", "fluted", "grip"],
  },
  {
    name: "Chicken Head",
    description: "Classic pointer knob for guitar amps",
    params: {
      diameter: 22,
      height: 12,
      shape: KnobShape.POINTER,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 10,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#ffffff",
      pointerIndent: false,
      pointerColor: "#000000",
      polygonSides: 6,
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 20,
    },
    tags: ["vintage", "pointer", "guitar"],
  },
  {
    name: "Hex Top Cap",
    description: "Two-tone knob with hexagonal cap",
    params: {
      diameter: 20,
      height: 16,
      shape: KnobShape.POLYGON,
      polygonSides: 6,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 13,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: true,
      capHeight: 5,
      capColor: "#ffd700",
      pointerIndent: false,
      pointerColor: "#ffffff",
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 18,
    },
    tags: ["modern", "two-tone", "polygon"],
  },
  {
    name: "Mini Speed Knob",
    description: "Small low-profile knob for tight spaces",
    params: {
      diameter: 14,
      height: 10,
      shape: KnobShape.CYLINDER,
      shaftType: ShaftType.ROUND,
      shaftDiameter: 6,
      shaftDepth: 8,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#000000",
      pointerIndent: true,
      pointerColor: "#ff0000",
      polygonSides: 6,
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 12,
    },
    tags: ["small", "minimal", "compact"],
  },
  {
    name: "Telecaster Style",
    description: "Vintage teardrop knob",
    params: {
      diameter: 18,
      height: 14,
      shape: KnobShape.DROP,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 11,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#000000",
      pointerIndent: false,
      pointerColor: "#ffffff",
      polygonSides: 6,
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 16,
    },
    tags: ["vintage", "guitar", "teardrop"],
  },
  {
    name: "HiFi Volume",
    description: "Large smooth knob with cap for high-end audio",
    params: {
      diameter: 28,
      height: 20,
      shape: KnobShape.CYLINDER,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6.35,
      shaftDepth: 16,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: true,
      capHeight: 6,
      capColor: "#c0c0c0",
      pointerIndent: true,
      pointerColor: "#ff0000",
      polygonSides: 6,
      fluteCount: 8,
      skirtHeight: 3,
      skirtDiameter: 32,
    },
    tags: ["large", "hifi", "premium"],
  },
  {
    name: "Octagon Grip",
    description: "Angular knob with excellent grip",
    params: {
      diameter: 19,
      height: 16,
      shape: KnobShape.POLYGON,
      polygonSides: 8,
      shaftType: ShaftType.D_SHAFT,
      shaftDiameter: 6,
      shaftDepth: 13,
      dFlatSize: 4.5,
      holeTolerance: 0.15,
      closedTop: true,
      hasCap: false,
      capHeight: 3,
      capColor: "#4a4a4a",
      pointerIndent: true,
      pointerColor: "#00ff00",
      fluteCount: 8,
      skirtHeight: 0,
      skirtDiameter: 17,
    },
    tags: ["polygon", "grip", "angular"],
  },
];
